# Numpy

#### Numpy is the core library for scientic computing in Python.

First, we import numpy as follows.

In [1]:
import numpy as np

__Basic Operations__

In [26]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)           # .shape returns a tuple (rows, columns)
print(a[0], a[1], a[2])  
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 3]


In [35]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(type(b))
print(b.shape)
print(b[0,1], b[1,1])  # accessing elements in multidimensional arrays
print(b)

<class 'numpy.ndarray'>
(2, 3)
2 5
[[1 2 3]
 [4 5 6]]


__Creating Arrays__

In [37]:
a = np.array([[4,5],[7,3]])
print(a)
b = np.zeros((3,2))      # zero 3 x 2
print(b)
c = np.ones((3,2))       # ones 3 x 2
print(c)
d = np.eye(2)            # identity 2 x 2
print(d)
e = np.random.random((2,2))
print(e)

[[4 5]
 [7 3]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.37332542  0.97743855]
 [ 0.65971713  0.62248968]]


__Slicing__

Let's try slicing on the follwing np.array

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

Slicing the first 2 rows and columns 1 and 2 (zero indexed)

In [39]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


Slicing the first 2 rows and taking all columns

In [42]:
c = a[:2,:] # a[:2,] also works
print(c)

[[1 2 3 4]
 [5 6 7 8]]


Taking the whole array a

In [46]:
d = a # a[:,:] also works 
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


__Note__ : Slicing does not make a new array but instead provides a view to the original array

In [47]:
# when d is changed, a is also changed
print(d[0,0], a[0,0])
d[0,0] = 2
print(d[0,0], a[0,0])

1 1
2 2


In [54]:
# since b corresponds to the first two rows and columns 1 and 2 of a
# indexing changes but they are views of same data
print(b[0,0], a[0,1])
b[0,0] = 42
print(b[0,0], a[0,1])
a[0,1] = 1
print(b[0,0], a[0,1])

1 1
42 42
1 1


__Integer Indexing with Slicing__

Consider the following 2D array

In [56]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

It is expected that the following two slicing syntaxes should yield the same result

In [57]:
b = a[1:2,:]
c = a[1,:]

But it turns out that __b__ and __c__ are different. __c__ is generated using integer indexing.

In [58]:
print(b, b.shape)
print(c, c.shape)

[[5 6 7 8]] (1, 4)
[5 6 7 8] (4,)


Mixing integer indexing with slices yields an array of lower raank, while using only slices always yields arrays of the same rank as original array.

Similarly we can try with column vectors.

In [59]:
e = a[:,1:2]
f = a[:,1]
print(e, e.shape)
print(f, f.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)
[ 2  6 10] (3,)


__Using integer array indexing to create arbitrary arrays__

When we index numpy arrays using slicing, the resulting array view will always be a subarray of the original array. Integer array indexing allows us to construct arbitrary arrays using data from another array.

Consider the following np.array

In [63]:
a = np.array([[1,2], [3,4], [5,6]])
b = a[[0, 1, 2], [0, 1, 0]]
# this takes out elements a[0,0], a[1,1] and a[2,0]
# same as np.array([a[0,0], a[1,1], a[2,0]])
print(b)
b[0] = 12
print(a[0,0], b[0])

[1 4 5]
1 12


When integer indexing is used, new array is created. Thus modifying one doesn't affect the other.

__Useful tricks with Integer array indexing__

Selecting one element from each row

In [72]:
b = np.array([0, 1, 0])
print(a[np.arange(3), b])

[1 4 5]


It prints __a[0,0]__, __a[1,1]__, __a[2,0]__

List of indexes can also be used.

In [73]:
b = [0, 1, 0]
print(a[np.arange(3), b])

[1 4 5]


We can also mutate one element from each row. Let's add 10 to the selected elements.

In [74]:
a[np.arange(3),b] += 10
print(a)

[[11  2]
 [ 3 14]
 [15  6]]


__Boolean array indexing__

Let's try boolean indexing on the following np.array

In [75]:
a = np.array([[1,2,12],[6,8,11]])

Now, we will create a boolean np.array, which will store result (true/false) in place of elements when the corresponding elements are fed to some boolean expression.

In [78]:
is_even = (a%2 == 0)
print(is_even)

[[False  True  True]
 [ True  True False]]


In [79]:
is_small = (a <= 6)
print(is_small)

[[ True  True False]
 [ True False False]]


These boolean arrays can be used as sieves to filter out elements with desirable properties. 

Let's take out all the event elements from __a__ using boolean array __is_even__.

In [83]:
print(a[is_even])

[ 2 12  6  8]


all the elements which are greater than 6:

In [88]:
is_big = (is_small == False)
print(a[is_big])

[12  8 11]


More examples:

In [89]:
print(a[a > 2]) # all elements greater than 2
print(a[a%2 == 1]) # all odd elements

[12  6  8 11]
[ 1 11]


__Datatypes in Numpy__